# TODO: Add comment
# 
# Author: claudio
###############################################################################

source("./base/lib/lists.R")
source("./base/lib/systemOptions.R")

source("./base/lib/repository.R")
source("./base/lib/importazioneDBPortfolioGenerale.R") 
source("./base/lib/genericFunctions.R")


source("./base/lib/classDefinitions/Amount/Amount.R")
source("./base/lib/classDefinitions/Currency/Currency.R") 
source("./base/lib/classDefinitions/Money/Money.R")
source("./base/lib/classDefinitions/Id/Id.R")
source("./base/lib/classDefinitions/Quantity/Quantity.R")

# source("./base/lib/classDefinitions/IdAyrton/IdAyrton.R")


#source("./base/lib/classDefinitions/AyrtonPosition/AyrtonPosition.R")
#source("./base/lib/classDefinitions/AyrtonPositions/AyrtonPositions.R")
#source("./base/lib/classDefinitions/AyrtonSecurity/AyrtonSecurity.R")
#source("./base/lib/classDefinitions/Constraint/Constraint.R") 
#source("./base/lib/classDefinitions/Strings/CheckString.R")
#source("./base/lib/classDefinitions/SelectionCriterium/SelectionCriteriaList.R")
#source("./base/lib/classDefinitions/Strings/DirectiveString.R")
#source("./base/lib/classDefinitions/Strings/CheckStringParsed.R")
#source("./base/lib/classDefinitions/Strings/ConstraintString.R")
#source("./base/lib/classDefinitions/Strings/FactorString.R")
#source("./base/lib/classDefinitions/Strings/FactorStrings.R")
#source("./base/lib/classDefinitions/Strings/SelectionString.R")
#source("./base/lib/classDefinitions/Strings/FactorStringParsed.R")

source("./base/lib/classDefinitions/Security/Security.R")
source("./base/lib/classDefinitions/Security/Bond.R")
source("./base/lib/classDefinitions/Security/Equity.R")
source("./base/lib/classDefinitions/Security/Fondi_obbligazionari.R")
source("./base/lib/classDefinitions/Security/Fondi_azionari.R")
source("./base/lib/classDefinitions/Security/Unclassified.R")
source("./base/lib/classDefinitions/Security/Conto_corrente.R")
source("./base/lib/classDefinitions/Security/Strutturati_FI.R")
source("./base/lib/classDefinitions/Security/Strutturati_EQ.R")
source("./base/lib/classDefinitions/Security/ETF_equity.R")
source("./base/lib/classDefinitions/Security/Metalli_preziosi.R")
source("./base/lib/classDefinitions/Security/FX_Forward.R")
source("./base/lib/classDefinitions/Security/Anticipi_fissi.R")
source("./base/lib/classDefinitions/Security/Futures_EQ.R")
source("./base/lib/classDefinitions/Security/Index_certificate.R")
source("./base/lib/classDefinitions/Security/Opzioni_su_azioni.R")
source("./base/lib/classDefinitions/Security/Fondi_immobiliari.R")
source("./base/lib/classDefinitions/Security/Fondi_Hedge.R")
source("./base/lib/classDefinitions/Security/ETF_commodities.R")
source("./base/lib/classDefinitions/Security/Depositi_a_termine.R")
source("./base/lib/classDefinitions/Security/Floating_rate_notes.R")
source("./base/lib/classDefinitions/Security/Fondi_misti.R")
source("./base/lib/classDefinitions/Security/Fondi_mercato_monetario.R")
source("./base/lib/classDefinitions/Security/Credit_linked_note.R")
source("./base/lib/classDefinitions/Security/Diritti_aumento_capitale_azionario.R")

#source("./base/lib/classDefinitions/SelectionCriterium/SelectionCriterium.R")
#source("./base/lib/classDefinitions/SelectionCriterium/SecuritySelectionCriterium.R")
#source("./base/lib/classDefinitions/SelectionCriterium/AmountSelectionCriterium.R")
#source("./base/lib/classDefinitions/SelectionCriterium/CurrencySelectionCriterium.R")
#source("./base/lib/classDefinitions/SelectionCriterium/MaturityHorizonSelectionCriterium.R")
#source("./base/lib/classDefinitions/SelectionCriterium/SelectionCriteria.R")
source("./base/lib/classDefinitions/FundDB/FundDB.R")
source("./base/lib/classDefinitions/FundRecord/FundRecord.R")
#source("./base/lib/classDefinitions/TestSuite/TestSuite.R")
#source("./base/lib/classDefinitions/TestSuiteCollection/TestSuiteCollection.R")


source("./base/lib/classDefinitions/Position/Position.R")
source("./base/lib/classDefinitions/Position/PositionEquity/PositionEquity.R")
source("./base/lib/classDefinitions/Position/PositionBond/PositionBond.R")
source("./base/lib/classDefinitions/Position/PositionFondi_misti/PositionFondi_misti.R")
source("./base/lib/classDefinitions/Position/PositionBond/AccruedInterest.R")
source("./base/lib/classDefinitions/Position/PositionFondiObbligazionariOC/PositionFondiObbligazionariOC.R")
source("./base/lib/classDefinitions/Positions/Positions.R")
source("./base/lib/classDefinitions/Portfolio/Portfolio.R")
source("./base/lib/classDefinitions/Portfolios/Portfolios.R")

source("./base/lib/methods/securityFactory/securityFactory.R") 
source("./base/lib/methods/positionFactory/positionFactory.R")
source("./base/lib/methods/positionFactory/createPosition.R")
source("./base/lib/methods/positionsFactory/positionsFactory.R")
#source("./base/lib/methods/positionsFactory/completePositionWithAccruedInterest.R")
#source("./base/lib/methods/positionsFactory/matchPositionToAyrtonPosition.R")
#source("./base/lib/methods/positionsFactory/adjustForAccruedInterest.R")
#source("./base/lib/methods/constraintFactory/constraintFactory.R")
#source("./base/lib/methods/selectionCriteriumFactory/selectionCriteriumFactory.R")
#source("./base/lib/methods/check/check.R")
#source("./base/lib/methods/selector/selector.R")
#source("./base/lib/methods/selector/filterByCriteria.R")
source("./base/lib/methods/idFactory/idFactory.R")

source("./base/lib/methods/portfolioFactory/portfolioFactory.R")
source("./base/lib/methods/portfoliosFactory/portfoliosFactory.R")

source("./base/lib/methods/parser/parser.R")
source("./base/lib/methods/explode/explode.R")
source("./base/lib/methods/Apply/Apply.R")
source("./base/lib/fundsDB.R")
source("./base/lib/identifyPositionsToExplode.R")
#source("./base/lib/methods/testSuiteFactory/testSuiteFactory.R")
#source("./base/lib/methods/applyTestSuite/applyTestSuite.R")
source("./base/lib/explodePortfolioByFund.R")

source("./ayrton/lib/library.R")
source("./riskman/lib/library.R")
